server:
  port: 9090

spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://127.0.0.1:4000/testdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true